import "../src/plugin";
import { calls, registry } from "./fake";
const m = registry["app.decksync.marker"]; const g = registry["app.decksync.goto"];
const ev = (dev: string, page: number, target?: number) => ({ action: { device: { id: dev }, setTitle: async () => {}, isKey: () => true, showOk: async () => {} }, payload: { settings: { page, target } } });
const log = (s: string) => console.log(s.padEnd(34), JSON.stringify(calls.splice(0)));
await m.onWillAppear(ev("A", 1)); log("A appears p1");
await m.onWillAppear(ev("B", 1)); log("B echo p1");
m.onWillDisappear(ev("A", 1)); await m.onWillAppear(ev("A", 2)); log("A -> p2");
m.onWillDisappear(ev("B", 1)); await m.onWillAppear(ev("B", 2)); log("B echo p2 (should be none)");
m.onWillDisappear(ev("B", 2)); await m.onWillAppear(ev("B", 3)); log("B user -> p3");
m.onWillDisappear(ev("A", 2)); await m.onWillAppear(ev("A", 3)); log("A echo p3 (none)");
m.onWillDisappear(ev("A", 3)); await m.onWillAppear(ev("A", 4, 1)); log("A p4 mapped -> B p1");
const gev = (dev: string, s: any) => ({ action: { device: { id: dev }, isKey: () => true, showOk: async () => {} }, payload: { settings: s } });
await g.onKeyDown(gev("B", { sd15: 2, plus: "" })); log("goto 15->2, + urort");
await g.onKeyDown(gev("B", { sd15: 2, plus: 2 })); log("goto begge -> 2");
m.onWillDisappear(ev("A", 4)); await m.onWillAppear(ev("A", 2)); log("A echo p2 (none)");
m.onWillDisappear(ev("B", 1)); await m.onWillAppear(ev("B", 2)); log("B echo p2 (none)");
const d = registry["app.decksync.dial"];
const dev = (id: string, p: any) => ({ action: { device: { id }, isDial: () => false, isKey: () => false }, payload: p });
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
await d.onDialRotate(dev("B", { ticks: 2 })); await wait(100); log("hjul +2 -> side 3 valgt, ingen sending");
d.onDialDown(dev("B", {})); await wait(50); d.onDialUp(dev("B", {})); await wait(50); log("kort trykk -> begge til side 3");
await d.onDialDown(dev("B", {})); await wait(650); await d.onDialUp(dev("B", {})); await wait(50); log("hold alene -> ingenting");
await d.onDialDown(dev("B", {})); await d.onDialRotate(dev("B", { ticks: 1, pressed: true })); await d.onDialUp(dev("B", {})); await wait(50); log("hold+vri -> mål A, ingen sending");
await d.onDialRotate(dev("B", { ticks: 1 })); await d.onDialDown(dev("B", {})); await wait(50); await d.onDialUp(dev("B", {})); await wait(50); log("side 4, kort trykk -> bare A");
await d.onDialDown(dev("B", {})); await d.onDialRotate(dev("B", { ticks: -1, pressed: true })); await d.onDialUp(dev("B", {})); await d.onDialDown(dev("B", {})); await wait(50); await d.onDialUp(dev("B", {})); await wait(50); log("hold+vri tilbake -> ALLE, trykk -> begge side 4");
const st = registry["app.decksync.step"];
await g.onKeyDown(gev("A", { all: 5 })); log("goto all -> 5");
await st.onKeyDown(dev("A", { settings: { mode: "next", scope: "all" } })); log("step next, all -> 6");
await st.onKeyDown(dev("A", { settings: { mode: "prev", scope: "this" } })); log("step prev, this -> A 5");
await g.onKeyDown(gev("A", { page_B: 2 })); log("goto per deck: B -> 2");
